# Generated by Django 2.2.4 on 2019-08-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20190501_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='nameserver',
            name='slug',
        ),
    ]
