# Generated by Django 2.2.4 on 2019-08-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_auto_20190829_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameserver',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameservers', to='domain.Domain'),
        ),
    ]
